### ISSUE TITLE
PositX1 conversion

### ISSUE THREAD

**Issue by milankl** [milankl/SoftPosit.jl#15]
Unfortunately, the PositX1 format (with 1 exponent bit, internally stored as 32bit) has poor conversion support. `Posit8_1(Posit32(1.23))` causes an error for example.

**Comment by giordano** [comment]
The problem is that `p32_to_pX1.o` [isn't built in the `Makefile`](https://gitlab.com/cerlane/SoftPosit/blob/56e55928fedd587375a47262234ec1ef40cabec9/build/Linux-x86_64-GCC/Makefile), probably because `p32_to_pX1.c` is broken

**Comment by milankl** [comment]
I'll ask Cerlane about that. Weird that she uploads the .c file still...

**Comment by giordano** [comment]
Probably it would be sufficient to define a couple of types, just like what is done for `p32_to_pX2.c`

**Comment by parthamaji** [comment]
+ Float64.(Posit8_1(0x0)) is not supported yet. Is that right?

**Comment by milankl** [comment]
Yes, that's right. [I've implemented the function already](https://github.com/milankl/SoftPosit.jl/blob/d859abd7babbb651749f62294069b94a9c9bbe61/src/conversionPositToFloat.jl#L12) but currently it tries to call a C function from the [SoftPosit C library](https://gitlab.com/cerlane/SoftPosit) that doesn't exist yet.

**Comment by parthamaji** [comment]
Thanks. Float64(Posit8_2(0x00)) helps. What about FloatXX(Posit16X(0x00))? It seems none of the Posit16 can be cast to Float for the time being. Is there any workaround possible?

**Comment by milankl** [comment]
Please note that for 16bit formats you need to use `UInt16` and not `UInt8`(also when encoded as hexadecimal), i.e.
```julia
julia> Float64(Posit16_2(0x5000))
4.0
julia> Float64(Posit16(0x5000))
2.0
```
This is briefly explained in the first section of the [notebook](https://github.com/milankl/SoftPosit.jl/blob/master/docs/softposit_examples.ipynb) that I've uploaded for the docs.

**Comment by milankl** [comment]
Given the independence of upcoming v0.5 with C-SoftPosit this issue is no longer relevant
