### ISSUE TITLE
Arithmetic operations: power

### ISSUE THREAD

**Issue by milankl** [milankl/SoftPosit.jl#16]
Sofar, things like `Posit16(1.23)^2` are not supported. I guess the best way would be to include promotion of integers to posits. The SoftPosit library does not have a power function but we might be able to implement this by a concatenation of multiplications/divisions. Priority on operations like power 2.

**Comment by giordano** [comment]
It works for me on GNU/Linux:
```julia
julia> Posit16(2.5) ^ 2
Posit16(0x6480)

julia> Float64(ans)
6.25
```

**Comment by milankl** [comment]
Haha, I also don't get an error, I wasn't expecting Julia to know how to Posit^2, but apparently this is internally translated to Posit*Posit, very smart Julia!
