### ISSUE TITLE
wrong sign function is called

### ISSUE THREAD

**Issue by milankl** [milankl/SoftPosit.jl#30]
@giordano Do you know why the sign function in src/constants.jl

```julia
function sign(p::Type{T}) where {T <: AbstractPosit}
    if signbit(p)       # negative and infinity case
        if isfinite(p)  # negative
            return minusone(T)
        else            # infinity
            return notareal(T)
        end
    else                # positive and zero case
        if iszero(p)    # zero
            return zero(T)
        else            # positive
            return one(T)
        end
    end
end
```

is not called for e.g. `sign(::Posit8)`?  Some other method (probably for the supertype `AbstractFloat` is called that returns for `sign(notareal(Posit8))` actually `Posit8(0xc0)` which is minus one (and makes sense in a float sense as the sign bit is actually negative). If, instead, I define sign(::Posit8) directly without parametric types it actually calls that method. I therefore assume that there is simply some conflict in the method preferences, which I currently don't understand. Any ideas?

**Comment by milankl** [comment]
@giordano I think a similar issue caused an error in `src/nextprevfloat.jl`, you see I've explicitly defined e.g. `nextfloat(::Posit8_2)` instead of defining methods for all posits at once using parametric types.

**Comment by giordano** [comment]
The signature is wrong, should be `function sign(p::T) where {T <: AbstractPosit}` :wink:

**Comment by milankl** [comment]
Damn it, yes, I don't want to define it for the type itself but for objects of that type. Related: `src/constants.jl` contains

```julia
one(::Type{T}) where {T<:PositAll8} = T(0x40)
```

such that `one(Posit8)` returns the 8bit posit one. However, I've never defined a `one(::Posit8)` directly, but `one(Posit8(1))` still works. Is that because Julia has somewhere defined a `one(x::AbstractFloat) = one(typeof(x))` ?

**Comment by giordano** [comment]
> I don't want to define it for the type itself but for objects of that type

Exactly!

> Is that because Julia has somewhere defined a `one(x::AbstractFloat) = one(typeof(x))` ?

Good guess:
```julia
julia> @which one(Posit8(1))
one(x::T) where T<:Number in Base at number.jl:298
```

And if you open `base/number.jl` in Julia, or you simply run the command `@less one(Posit8(1))`, you'll find this definition:
```julia
one(x::T) where {T<:Number} = one(T)
```

**Comment by milankl** [comment]
What is the problem with `function sign(p::T) where {T <: Union{Type1,Type2,Type3})` somehow that doesn't work as expected.

**Comment by milankl** [comment]
@giordano One more thing that I don't understand (Thanks so much for all your help!). Currently, we have
```julia
for T in (:Posit8_2, :Posit16_2, :Posit24_2)
    @eval begin
        round(x::$T) =  ccall((:pX2_roundToInt, SoftPositPath), $T, ($T,),x)
    end
end
```
which works fine. However, I thought the following is equivalent:
```julia
julia> round(x::T) where {T<:PositX2} =  ccall((:pX2_roundToInt, SoftPositPath), T, (T,),x)
ERROR: TypeError: in ccall method definition, expected Type, got TypeVar
```
with `PositX2 = Union{Posit8_2,Posit16_2,Posit24_2}`, but apparently it's not. Any clue?

**Comment by giordano** [comment]
Honestly I never came across this issue, but I just found that it's explained in the [documentation](https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/#Type-Parameters-1)

> However, while the type layout must be known statically to compute the intended C ABI, the static parameters of the function are considered to be part of this static environment. The static parameters of the function may be used as type parameters in the call signature, as long as they don't affect the layout of the type. For example, `f(x::T) where {T} = ccall(:valid, Ptr{T}, (Ptr{T},), x)` is valid, since `Ptr` is always a word-size primitive type. But, `g(x::T) where {T} = ccall(:notvalid, T, (T,), x)` is not valid, since the type layout of `T` is not known statically.

The `@eval` allows you to work around this, as the type "becomes static" when you evaluate the expression.

**Comment by milankl** [comment]
I see, but using `Ptr{T}` instead of simply `T` should then work too, right?

**Comment by giordano** [comment]
It should, if the C function signature allows it

**Comment by milankl** [comment]
Apparently not,
```julia
ERROR: MethodError: no method matching unsafe_convert(::Type{Ptr{Posit16_1}}, ::Posit16_1)
```
I'll just leave it the way it is, it doesn't really make a difference anyway!
