### ISSUE TITLE
Why sizeof(Posit8_1) == 4?

### ISSUE THREAD

**Issue by adamryczkowski** [milankl/SoftPosit.jl#47]
I feel I missed something obvious. Shouldn't `sizeof(Posit8_x)==1` for all `x`?

On the other hand, `sizeof(Posit8)==1`, as expected. Can you explain it to me, or point to the documentation?

Steps to reproduce:

```
using Pkg
Pkg.add(PackageSpec(url="https://github.com/milankl/SoftPosit.jl"))
using SoftPosit
sizeof(Posit8_1)

```

**Comment by milankl** [comment]
Yes, thereotically. However, only the standard types `Posit8, Posit16, Posit32` with (0,1,2 exp bits) are implemented that way (src/typedef.jl)

```julia
primitive type Posit8 <: AbstractPosit 8 end
primitive type Posit16 <: AbstractPosit 16 end
primitive type Posit32 <: AbstractPosit 32 end
```
The non-standard types like Posit8_1, Posit8_2 but also Posit24_2 all have 32bit under the hood, as the underlying C-library implemented them with filling zeros. This means that 32bit are used for storing only (where the remaining bits are always zero)

```julia
julia> Posit8_2(1.23456789)
Posit8_2(0x42000000)
julia> Float64(ans)
1.25
```
`Posit8_2` for example gives you exactly the 8bit of precision that it should have for computations. This is to allow a greater flexibility with the SoftPosit library, in case someone wants to experiment with Posit(12,2) or something odd. If you want to use a real 8bit type you are currently restricted to `Posit8` (with 0 exponent bits).
