### ISSUE TITLE
Is there a plan to support ^ operator?

### ISSUE THREAD

**Issue by chunjiw** [milankl/SoftPosit.jl#53]
The C library seems to support ^.

**Comment by milankl** [comment]
If the C library supports it, then it should be easy to implement. I'll have a look at it next week. Note that ^(::Posit,::Int) is already supported as Julia translates that to *On 7 Jan 2020 02:49, Chunji Wang <notifications@github.com> wrote:The C library seems to support ^.

**Comment by milankl** [comment]
e.g.
```julia
julia> using SoftPosit
julia> a = Posit16(1.2)
Posit16(0x4333)
julia> a^2
Posit16(0x470a)
julia> Float64(a^2)
1.43994140625
```

**Comment by chunjiw** [comment]
Thank you for the hard work! It's good that ^(::Posit, ::Int) is in place. But I am trying to compare Posit32 to Float32, it would be great if I can use ^(::Posit, ::Posit).

**Comment by milankl** [comment]
I see that Cerlane wrote in in the [readme](https://gitlab.com/cerlane/SoftPosit#main-functionalities) that the ^ operator is supported, but I can't find it the associated function in the repository. Maybe that was planned but never completed?

I'm unsure whether ^ would come with error-free rounding (i.e. the closest representable posit to the true result), if, then we could simply implement ^ via back&forth promotion.

```julia
^(x::T,y::T) where {T<:AbstractPosit} = T(^(Float64(x),Float64(y)))
```

**Comment by milankl** [comment]
Just checked, ^ for floats does not come with error-free rounding:

```julia
using Test

@testset "Error-free pow?" begin

    X = randn(100).^2
    Y = randn(100).^2

    @testset for (r1,r2) in zip(X,Y)
        r1f32 = Float32(r1)
        r2f32 = Float32(r2)

        @test Float32(r1^r2) == r1f32^r2f32
    end
end
```
In my case this was
```julia
Test Summary:                                               | Pass  Fail  Total
Error-free pow?                                             |   69    31    100
```

**Comment by chunjiw** [comment]
Thank you for the comment! I learned a lot. I can use back and forth approach in my project for the moment.
