### ISSUE TITLE
Comparison

### ISSUE THREAD

**Issue by pevnak** [milankl/SoftPosit.jl#71]
Is this a correct behavior?
```
julia> Posit8(1.f0) > 0
false

julia> Posit8(1.f0) < 0
true
```

**Comment by milankl** [comment]
Haha, no, of course not. I've just created pr #72 which should address these and add more meaningful tests for comparisons. Now we use 
```julia
Base.:(<)(x::T,y::T) where {T<:AbstractPosit} = signed(x) < signed(y)
```
which works between -maxpos and maxpos simply by reinterpreting the posit bits as signed integer. `0b1111_1111` is -1 in Int8, so we essentially map posits as if we numerated them, starting at 0 and positive 1,2,3,4,... for positive posits and negative -1,-2,-3,... for negative posits.

**Comment by milankl** [comment]
How's comparison with NaR defined for posit arithmetic?

**Comment by milankl** [comment]
![image](https://user-images.githubusercontent.com/25530332/193308603-880116ae-e16f-4391-ac7e-ff0eb90a7c5c.png)

Quick check
```julia
julia> Posit8(0x81)
Posit8(-1.6777216e7)

julia> Posit8(0x81) > notareal(Posit8)
true

julia> Posit8(-1f0) > notareal(Posit8)
true

julia> Posit8(0f0) > notareal(Posit8)
true

julia> Posit8(1f0) > notareal(Posit8)
true

julia> Posit8(0x7f)
Posit8(1.6777216e7)

julia> Posit8(0x7f) > notareal(Posit8)
true
```
looks good 👍🏼

**Comment by milankl** [comment]
The fix from #72  should be released soon as v0.5.1

**Comment by milankl** [comment]
@pevnak thanks for spotting this.

**Comment by pevnak** [comment]
Great. I have discovered it during teaching. It was a bit hiccup.

**Comment by milankl** [comment]
Ha, sorry for that, but I hope an example how the open source hivemind works.
